### ISSUE TITLE
Line Number Font doesn't scale properly

### ISSUE THREAD

**Issue by charlesm93** [abrochard/emacs-config#1]
Let's say I want to see line numbers:
`M-x linum-mode`

And I also want to increase the font:
`C-x C+`

The font of the line number increases too, but the margin, in which the line numbers are written doesn't. As a result, the margin crops out line numbers and I end up seeing, say, 1 instead of 10, 11, 12, etc. It'd be nice to have the line-numbers scale in this emacs config.

This isn't a new problem. Here are some proposed solutions, see: http://unix.stackexchange.com/questions/29786/font-size-issues-with-emacs-in-linum-mode/30087#30087

I'm happy to attempt a fix, but, a fair heads up, I'm not super familiar with emacs, and adding new scripts to a config.

**Comment by abrochard** [comment]
That's a good find. I never use `linum-mode` and instead use the `M-g g` command to jump to a line.

But if this is a problem for you, you can try the code snippet proposed at https://www.emacswiki.org/emacs/LineNumbers#toc14 which seems a lot simpler.
I've noticed a couple of bugs while testing it just now, but let me know what you think. 

To test it, copy paste it into the scratch buffer and use the command `C-c x` or `M-x eval-buffer`

**Comment by charlesm93** [comment]
About time we close this issue!

**Comment by abrochard** [comment]
Yeah with recent emacs 25 release we have built-in line number mode now.

**Comment by charlesm93** [comment]
Cool. Guess I should update the emac on my local machine then.
